version: "3.8"

services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - neobank-net

  app:
    build: ./neobank-app
    image: neobank-app:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8081/realms/neobank
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/neobank/protocol/openid-connect/certs
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - neobank-net
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file

    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
        - neobank-net
volumes:
  postgres_data:
  keycloak_data:

networks:
  neobank-net:
